export const LOTTERY_NAMES: string[] = [
  'El Afortunado', 'La Suerte Dorada', 'Trébol de la Fortuna', 'Estrella Fugaz',
  'El Ganador', 'Número de Oro', 'Corona de la Suerte', 'Rayo Afortunado',
  'Diamante Brillante', 'El Elegido', 'Fortuna Salvaje', 'Luna de la Suerte',
  'Cometa Dorado', 'El Milagroso', 'Tesoro Escondido', 'Piedra Filosofal',
  'Cuerno de la Abundancia', 'Fénix Renacido', 'Amuleto Sagrado', 'El Predestinado',
  'Corazón de Oro', 'Llama de la Fortuna', 'Dragón de la Suerte', 'Aurora Boreal',
  'El Imbatible', 'Cofre del Tesoro', 'Manantial de Riqueza', 'Sol Radiante',
  'Espada de la Fortuna', 'El Victorioso', 'Relámpago Dorado', 'La Providencia',
  'Oasis de Suerte', 'El Invencible', 'Perla del Destino', 'Río de Oro',
  'La Bendecida', 'Faro de la Fortuna', 'El Renacido', 'Cima Afortunada',
  'Ala de la Suerte', 'El Campeón', 'Espejo de la Dicha', 'Sendero Dorado',
  'La Iluminada', 'Trueno Afortunado', 'El Magnífico', 'Joya del Destino',
  'Brisa de la Fortuna', 'La Soñadora', 'Guardián de la Suerte', 'Estrella Polar',
  'El Triunfador', 'Cáliz de la Dicha', 'La Prometida', 'Arco de la Fortuna',
  'El Brillante', 'Néctar Dorado', 'Sombra Afortunada', 'La Dichosa',
  'Viento de la Suerte', 'El Insuperable', 'Fuente de Riqueza', 'Reliquia Dorada',
  'La Encantada', 'Talismán de Oro', 'El Privilegiado', 'Estela de la Fortuna',
  'La Radiante', 'Portal de la Suerte', 'El Admirable', 'Gema del Destino',
  'La Inesperada', 'Cauce de la Dicha', 'El Poderoso', 'Alborada Dorada',
  'La Consentida', 'Marea de la Fortuna', 'El Extraordinario', 'Lucero del Alba',
  'La Renovada', 'Brasa de la Suerte', 'El Favorito', 'Nube Dorada',
  'La Bienaventurada', 'Rosa de la Fortuna', 'El Agraciado', 'Cristal de la Dicha',
  'La Elegida', 'Torbellino de Oro', 'El Prodigioso', 'Semilla de la Suerte',
  'La Resplandeciente', 'Anillo del Destino', 'El Predilecto', 'Colmena de Oro',
  'La Venturosa', 'Sello de la Fortuna', 'El Espléndido', 'La Celestial'
];